Forms validation added
AnatolyKyznetsov/game pull request #10
Opened 2023-04-26 19:19 UTC by KatrinYandex

Добавлена валидация форм.

2023-04-26 23:00 UTC, likeariverstream reviewed
Хорошая логика валидации, код чистый и лаконичный

2023-04-28 00:53 UTC, likeariverstream commented on packages/client/src/utils/validator.ts
> +export function validator(string: string | undefined, type: string, secondString?: string | undefined) {
Опциональный параметр и так имеет тип ... | undefined, поэтому можно так:
 interface Validator {
    (string: string | undefined,
        type: string,
        secondString?: string): boolean
}
export const validator: Validator = (string, type, secondString) => {...

2023-04-28 00:54 UTC, likeariverstream approved these changes

2023-04-28 09:05 UTC, AnatolyKyznetsov requested changes

2023-04-28 09:05 UTC, AnatolyKyznetsov commented on packages/client/src/utils/validator.ts
> +        break
По моему ошибка в регулярке. Я скидывал правильные вместе с версткой в пачку.

2023-04-28 10:08 UTC, KatrinYandex commented on packages/client/src/utils/validator.ts
> +        break
> По моему ошибка в регулярке. Я скидывал правильные вместе с версткой в пачку.

У меня мои варианты проходят, может какой-то выброс попался. Окей, для пароля заменю.

2023-04-28 10:10 UTC, KatrinYandex commented on packages/client/src/pages/RegisterPage.tsx
> +                    <a href='/login' className='link shape__link'>Войти</a>
Ты имеешь в виду, Link как компонент? или просто тэг link?

2023-04-28 10:18 UTC, KatrinYandex commented on packages/client/src/pages/LoginPage.tsx
> +                            onClick={handleClick}/>
Не заметила комментарий до этого

2023-04-28 14:05 UTC, AnatolyKyznetsov approved these changes

2023-04-29 11:51 UTC, RodionBozhenko commented on packages/client/src/components/Input.tsx
> +export const Input = forwardRef((inputProps: InputProps, ref: ForwardedRef<HTMLInputElement>) => {
Для удобочитаемости кода пропсы лучше деструктуризировать. 
``` 
const {name, type, error, tooltip, label} = inputProps
```
Это конечно мелочь, но так как из контекста понятно, что пропсы относятся к компоненту Input, то называть их inputProps излишне, достаточно просто props

2023-04-29 11:56 UTC, RodionBozhenko commented on packages/client/src/components/Input.tsx
> +    const hasTooltip = () => {
Здесь тоже можно улучшить нейминг. Функции, начинающиеся с has, is, как правило, возвращают булево значение. Эта же функция возвращает tooltip, поэтому лучше назвать ее addTooltip. Опять же это незначительно, но как миддл разработчику стоит стараться соответствовать "канонам" чистого кода)

2023-04-29 11:57 UTC, RodionBozhenko commented on packages/client/src/interfaces.ts
> +    tooltip: string,
Так как в Инпуте у тебя проверка на тултип, то предполагается, что он необязательный пропс

2023-04-29 12:01 UTC, RodionBozhenko commented on packages/client/src/pages/LoginPage.tsx
> +    }
Тут тоже можно улучшить читаемость кода. Такие вещи как !Object.values(validateFields()).includes(true) сложно читаются. Можно изменить функцию validateFields таким образом, чтобы она возвращала не объект с булевыми значениями, а само булево значение. Тогда код будет выглядеть понятнее. 
```
const onSubmitForm = (e: FormEvent) => {
        e.preventDefault();
        const fieldsValidated = validateFields()
        if (fieldsValidated) {
            navigator(Paths.main)
        }
    }

    const validateFields = () => {
        const newErrorFields = {
            login: !validator(loginRef.current?.value, 'login'),
            password: !validator(passwordRef.current?.value, 'password')
        }
        setErrorFields(newErrorFields);

        return !Object.values(newErrorFields).includes(true)
    }
```

2023-04-29 12:03 UTC, RodionBozhenko commented on packages/client/src/pages/LoginPage.tsx
> +    const navigator = useNavigate();
Лучше заменить navigator на navigate как описано в доках реакт роутера, потому что navigator - это отдельное браузерное апи. Это поможет избежать путаницы

2023-04-29 12:03 UTC, RodionBozhenko commented on packages/client/src/pages/RegisterPage.tsx
>  export function RegisterPage() {
В этом компоненте те же небольшие проблемы, что описал для LoginPage

2023-04-29 12:06 UTC, RodionBozhenko requested changes
В целом все замечательно! Хорошая работа. Описал правки. Правки все незначительные и необходимы только для улучшения читаемости кода. И все же важно держать в голове необходимость поддержания чистоты кода даже в таких мелочах как названия переменных, функций и компонент.

2023-05-03 07:19 UTC, RodionBozhenko approved these changes
👍

2023-05-03 08:12 UTC, merged