Gam 22 - Вёрстка экрана игры Начало
AnatolyKyznetsov/game pull request #13
Opened 2023-04-28 07:04 UTC by AnatolyKyznetsov

Реализовано: 
- страница начала игры
- компонент меню и его элемента

Меню управляется с клавиатуры.
Добавил новый шрифт и фоновую картинку.
Изменил 2 цвета в стилях.

2023-05-01 04:22 UTC, likeariverstream reviewed
Хорошо подобраны шрифты и картинки, код делает то, что должен. Удаляются обработчики событий

2023-05-01 04:22 UTC, likeariverstream commented on packages/client/src/components/Menu.tsx
> +            window.removeEventListener('keydown', handleKeyPressArrow);
Отлично, что правильно удаляются обработчики

2023-05-01 04:22 UTC, likeariverstream commented on packages/client/src/components/Menu.tsx
> +                        <MenuItem key={key} index={key} isActive={key === activeIndex} title={item.title} url={item.url} clickHandeler={item.clickHandeler} mouseEnterHandeler={handleMouseEneter} />
Лучшим решением будет назначить элементам массива и использовать для ключей уникальные id, а не индексы массива https://react.dev/learn/rendering-lists#rules-of-keys

2023-05-01 06:12 UTC, AnatolyKyznetsov commented on packages/client/src/styles/components/menu.scss
> +    margin-top: 60px;
Тут не соглашусь. Я задаю отступ между элементами, а не отодвигаю контент от края. Например представь что у меню появился фон, тогда становится видно что padding для этого не подойдет.

2023-05-01 07:06 UTC, likeariverstream commented on packages/client/src/components/Menu.tsx
> +    const id = makeId();
Это неверное место для генерации ключа. Уникальный ключ будет создаваться каждый раз при ререндере меню, что приведет к ошибкам рендера https://disk.yandex.ru/i/KCaoMzjXDeInyw
Можно генерировать ключ при объявлении константы: 
<code>
    const menuItems = [
        { title: 'Новая игра', url: Paths.game },
        { title: 'Форум', url: Paths.feed },
        { title: 'Профиль', url: Paths.profile },
        { title: 'Выход', url: Paths.login }
    ].map((item) => {
        return { ...item, id: makeId() }
</code>
или добавить id руками

2023-05-01 07:32 UTC, likeariverstream approved these changes

2023-05-03 08:20 UTC, RodionBozhenko commented on packages/client/src/components/Menu.tsx
> +    );
Здесь useCallback излишен, потому что эта функция не прокидывается как пропс в компонент. Таким образом мемоизация здесь может скорее сделать хуже, чем лучше.

2023-05-03 08:20 UTC, RodionBozhenko commented on packages/client/src/components/Menu.tsx
> +    )
Опечатка в названии функции. И та же ситуация с мемоизацией, что и в handleKeyPressEnter

2023-05-03 08:23 UTC, RodionBozhenko commented on packages/client/src/components/Menu.tsx
> +    }, [ activeIndex ]);
Здесь лучше убрать activeIndex из зависимостей, иначе на каждое изменение этого стейта, слушатели будут по новой добавляться, что вряд ли сделано специально

2023-05-03 08:25 UTC, RodionBozhenko commented on packages/client/src/components/Menu.tsx
> +            }
Здесь не очень критично, но в качестве хорошей практики лучше переделать это на проверку типа элемента 
```
            const target = e.target;
            if (target instanceof HTMLElement && target.dataset.index) {
                setActiveIndex(Number(target.dataset.index));
            }
```

2023-05-03 08:26 UTC, RodionBozhenko commented on packages/client/src/components/MenuItem.tsx
> +export const MenuItem = ({ title, url, index, clickHandeler, mouseEnterHandeler, isActive }: MenuItemProps) => {
Опечатка в clickHandeler и mouseEnterHandeler

2023-05-03 08:27 UTC, RodionBozhenko requested changes
В целом 👍 но есть, что улучшить. Оставил комментарии

2023-05-03 10:53 UTC, RodionBozhenko approved these changes
👍

2023-05-07 09:36 UTC, IYDoe approved these changes

2023-05-12 09:44 UTC, merged