gam-18 верстка страницы форума
AnatolyKyznetsov/game pull request #15
Opened 2023-04-30 17:11 UTC by likeariverstream

### верстка страницы форума - поле ввода, кнопка и сообщения. данные пользователя пока что фейк

2023-05-02 08:05 UTC, AnatolyKyznetsov commented on lerna-debug.log
> +3 error     at AddCommand.initialize (C:\Users\админ\dev\game\node_modules\@lerna\add\index.js:46:17)
Добавь этот файл в gitignore

2023-05-02 08:38 UTC, likeariverstream commented on lerna-debug.log
> +3 error     at AddCommand.initialize (C:\Users\админ\dev\game\node_modules\@lerna\add\index.js:46:17)
Добавил и удалил этот файл

2023-05-02 08:54 UTC, AnatolyKyznetsov approved these changes

2023-05-03 07:55 UTC, RodionBozhenko requested changes
Все замечательно👍 За тем исключением, что я не рекомендую так обращаться с состоянием инпутов 
```
onChange={(e) => setCommentText(e.target.value)}
```
Для таких вещей лучше использовать React Hook Form. 
Если не использовать такие библиотеки - это решение команды, то можно тогда поменять onChange на onBlur. Таким образом, изменять стейт только тогда, когда пользователь закончил вводить текст. При подходе с onChange стейт компонента будет меняться на каждый вводимый символ и весь компонент будет перерендериваться также на каждый вводимый в инпут символ.

2023-05-03 07:56 UTC, RodionBozhenko commented on packages/client/src/pages/ForumPage/components/CommentItem.tsx
> +    const formatedDate = getDateToLocale(date)
Надо поменять на formattedDate

2023-05-03 16:17 UTC, likeariverstream commented on packages/client/src/pages/ForumPage/components/CommentItem.tsx
> +    const formatedDate = getDateToLocale(date)
Исправил

2023-05-04 14:59 UTC, RodionBozhenko approved these changes
👍

2023-05-05 07:24 UTC, merged