Gam 30
AnatolyKyznetsov/game pull request #20
Opened 2023-05-19 17:44 UTC by KatrinYandex

Добавлена логика авторизации, авторизация реализована через hook

2023-05-20 07:29 UTC, likeariverstream reviewed
Работа отличная, реализован кастомный хук и авторизация, осталось немного поправить

2023-05-20 07:29 UTC, likeariverstream commented on packages/client/src/pages/LoginPage.tsx
> +            dispatch(getUserInfo());
Здесь есть риск получить другого пользователя

2023-05-20 07:29 UTC, likeariverstream commented on packages/client/src/store/slices/userSlice/actions.ts
> +        credentials: 'include',
Здесь не отправляем данные

2023-05-20 07:29 UTC, likeariverstream commented on packages/client/src/store/slices/userSlice/actions.ts
> +    }
Лучше добавить обработку ошибок

2023-05-20 07:29 UTC, likeariverstream commented on packages/client/src/utils/authorizationHook.ts
> +    const isAuth = useAppSelector((state: RootState) => state.user);
Стейт типизирован, нужно только добавить в него isAuth

2023-05-20 07:39 UTC, KatrinYandex commented on packages/client/src/pages/LoginPage.tsx
> +import { useAuthorization } from '../utils/authorizationHook'
На какое?

2023-05-20 07:40 UTC, KatrinYandex commented on packages/client/src/pages/LoginPage.tsx
> +            dispatch(getUserInfo());
Почему же? Пользователя получаем по запросу, в который вложены куки.

2023-05-20 07:40 UTC, KatrinYandex commented on packages/client/src/utils/authorizationHook.ts
> +    const isAuth = useAppSelector((state: RootState) => state.user);
Ты имеешь в виду, что в целом добавить поле isAuth в state?

2023-05-20 08:49 UTC, likeariverstream commented on packages/client/src/pages/LoginPage.tsx
> +import { useAuthorization } from '../utils/authorizationHook'
useAuthorization

2023-05-20 09:20 UTC, likeariverstream commented on packages/client/src/pages/LoginPage.tsx
> +            dispatch(getUserInfo());
Нет гарантии что не будет логина нового пользователя и нет гарантии что логин будет выполнен до getUserInfo

2023-05-20 09:22 UTC, likeariverstream commented on packages/client/src/utils/authorizationHook.ts
> +    const isAuth = useAppSelector((state: RootState) => state.user);
Да, добавить его туда явно. Сейчас весь стейт из userSlice - это isAuth

2023-05-20 09:28 UTC, KatrinYandex commented on packages/client/src/utils/authorizationHook.ts
> +    const isAuth = useAppSelector((state: RootState) => state.user);
Так и сделала по итогу)

2023-05-20 09:28 UTC, KatrinYandex commented on packages/client/src/pages/LoginPage.tsx
> +            dispatch(getUserInfo());
Тогда как предлагаешь это реализовать? Пока что у меня логин проскакивал до getUserInfo

2023-05-20 09:36 UTC, IYDoe commented on packages/client/src/pages/LoginPage.tsx
> +import { useAuthorization } from '../utils/authorizationHook'
Я бы еще вынес если это хук, в отделью папку с хуками, например hooks

2023-05-20 10:08 UTC, KatrinYandex commented on packages/client/src/pages/LoginPage.tsx
> +import { useAuthorization } from '../utils/authorizationHook'
> Я бы еще вынес если это хук, в отделью папку с хуками, например hooks

У нас они уже по разным местам раскиданы, но согласна

2023-05-20 10:15 UTC, likeariverstream commented on packages/client/src/pages/LoginPage.tsx
> +            dispatch(getUserInfo());
Async/await или цепочка обработчиков для этих функций)

2023-05-20 11:00 UTC, likeariverstream approved these changes

2023-05-21 09:54 UTC, IYDoe approved these changes

2023-05-21 14:57 UTC, RodionBozhenko commented on packages/client/src/pages/RegisterPage.tsx
> +                password: (passwordRef.current as HTMLInputElement).value
Вместо утверждения типа здесь лучше сделать опциональную цепочку:
```
 (emailRef.current as HTMLInputElement).value -->  emailRef.current?.value,
```
Тайпскрипт ругается на то, что emailRef.current может быть нал, потому что начальное значение рефа - нал

2023-05-21 14:58 UTC, RodionBozhenko requested changes
Все хорошо, оставил один комментарий

2023-05-21 15:07 UTC, KatrinYandex commented on packages/client/src/pages/RegisterPage.tsx
> +                password: (passwordRef.current as HTMLInputElement).value
Тогда нужно будет дополнительно указать secondNameRef.current?.value as string, потому что на вход ожидается string и в этом место поле обязательно будет не null

2023-05-21 15:13 UTC, RodionBozhenko approved these changes
👍

2023-05-21 15:13 UTC, merged