gam-23 - Верстка страницы пользователя
AnatolyKyznetsov/game pull request #21
Opened 2023-05-20 09:28 UTC by IYDoe

Верстка страницы пользователя, подключение API

2023-05-20 12:20 UTC, likeariverstream approved these changes

2023-05-21 14:45 UTC, RodionBozhenko commented on packages/client/src/pages/EditProfilePage.tsx
> +                        </div>
Лучше вынести в отдельный компонент, чтобы не было такой вложенности

2023-05-21 14:47 UTC, RodionBozhenko commented on packages/client/src/pages/EditProfilePage.tsx
> +                        <div>Loading...</div>
Вот этот код лучше вынести в компонент перед основной версткой:
```
if (isLoading) return <div>Loading...</div>
```

2023-05-21 14:48 UTC, RodionBozhenko commented on packages/client/src/pages/ProfilePage.tsx
> +                        <div>Loading...</div>
Тут тоже самое, что и в EditProfilePage компоненте

2023-05-21 14:50 UTC, RodionBozhenko commented on packages/client/src/store/selectors/userSelectors.ts
> +export const selectIsLoadingUser = createSelector([ selectUser ], user => user.isLoading)
Эти комментарии излишни, так как они повторяют название функции selectUserData и selectIsLoadingUser. Функции говорят сами за себя

2023-05-21 14:51 UTC, RodionBozhenko requested changes
Все здорово, оставил несколько комментариев

2023-05-21 15:15 UTC, RodionBozhenko approved these changes
👍

2023-05-21 15:48 UTC, merged