gam-43 - Добавлен Gamepad API
AnatolyKyznetsov/game pull request #35
Opened 2023-06-12 10:30 UTC by IYDoe

Добавлен Gamepad API

2023-06-13 05:51 UTC, AnatolyKyznetsov requested changes
Всё ок, но надо подключить это api к игре. Всё управление происходит в packages/client/src/engine/Control.ts

2023-06-14 05:54 UTC, IYDoe commented
@AnatolyKyznetsov да я бы и рад, но проблема в том что у меня нет джостика, и мне даже проверить это негде

2023-06-14 06:17 UTC, AnatolyKyznetsov commented
Тогда надо выбрать другое api

2023-06-14 15:37 UTC, RodionBozhenko commented on packages/client/src/utils/hooks/useGamepad.ts
> +        }
Надо еще отменять анимейшн фрейм при размонтировании
```
        animationFrameId = requestAnimationFrame(animationFrame)

        return () => {
            window.removeEventListener('gamepadconnected', connectHandler)
            window.removeEventListener('gamepaddisconnected', disconnectHandler)
            if (animationFrameId) {
                cancelAnimationFrame(animationFrameId)
            }
```

2023-06-14 15:58 UTC, RodionBozhenko commented on packages/client/src/utils/hooks/useGamepad.ts
> +        }
Стейт сеттается каждый раз, когда requestAnimationFrame вызывается, что может быть очень часто. Это может привести к частому ререндеру компонента, где используется этот хук. Чтобы уменьшить эти ререндеры надо сравнивать предыдущий стейт геймпада с новым
        const updateHandler = () => {
            const connectedGamepads = navigator.getGamepads()
            for (const connectedGamepad of connectedGamepads) {
                if (connectedGamepad && (!gamepad || gamepad.index === connectedGamepad.index)) {
                    setGamepad(prev => prev !== connectedGamepad ? connectedGamepad : prev)
                    break
                }
            }
        }

2023-06-14 16:00 UTC, RodionBozhenko commented on packages/client/src/utils/hooks/useGamepad.ts
> +            console.log('Gamepad connected:', gamepad)
Логгирование надо почистить, такое не стоит заливать в прод

2023-06-25 07:07 UTC, AnatolyKyznetsov approved these changes

2023-06-25 17:56 UTC, RodionBozhenko approved these changes
👍

2023-06-26 01:57 UTC, merged